'use client';
import { useEffect, useState } from 'react';
import { getSupabaseClient } from '@/lib/supabaseClient';
import type { ProjectInquiry } from '@/lib/types';

export default function AdminInquiryDetail({id}:{id:string}){const [row,setRow]=useState<ProjectInquiry|null>(null); const load=async()=>{const s=getSupabaseClient();const {data}=await s.from('project_inquiries').select('*').eq('id',id).single(); setRow(data as ProjectInquiry);}; useEffect(()=>{load();},[id]);
const patch=async(status:ProjectInquiry['status'])=>{const s=getSupabaseClient(); const {data:{session}}=await s.auth.getSession(); await fetch(`/api/project-inquiries/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify({status})}); await load();};
if(!row) return <p>Memuat detail...</p>; return <div className='space-y-4'><div className='grid gap-2'>{[['Nama',row.nama],['Perusahaan / Brand / Instansi',row.perusahaan||'—'],['Email',row.email||'—'],['WhatsApp',row.whatsapp||'—'],['Jenis kebutuhan',row.jenis_kebutuhan],['Lokasi project',row.lokasi_project||'—'],['Estimasi luas',row.estimasi_luas||'—'],['Tahap project',row.tahap_project||'—'],['Timeline',row.timeline||'—'],['Budget range',row.budget_range||'—'],['Status file',row.status_file||'—'],['Kebutuhan utama',row.kebutuhan_utama],['Message preview',row.message_preview],['Created at',new Date(row.created_at).toLocaleString('id-ID')],['Current status',row.status]].map(([k,v])=><p key={String(k)}><span className='text-white/60'>{k}:</span> {String(v)}</p>)}</div>
<div className='flex flex-wrap gap-3'><button onClick={()=>navigator.clipboard.writeText(row.message_preview)}>Copy WhatsApp message</button>{row.whatsapp?<a href={`https://wa.me/${row.whatsapp.replace(/[^\d]/g,'')}?text=${encodeURIComponent(row.message_preview)}`} target='_blank'>Open WhatsApp</a>:null}<button onClick={()=>patch('ditinjau')}>Mark as Ditinjau</button><button onClick={()=>patch('dihubungi')}>Mark as Dihubungi</button><button onClick={()=>patch('selesai')}>Mark as Selesai</button><button onClick={()=>patch('arsip')}>Arsipkan</button></div></div>;}
