'use client';
import { useEffect, useState } from 'react';
import { createSupabaseBrowserClient } from '@/lib/supabase';
import type { ProjectInquiry } from '@/lib/types';

export default function AdminInquiryDetail({ id }: { id: string }) {
  const [row, setRow] = useState<ProjectInquiry | null>(null); const [error, setError] = useState(''); const [copyState, setCopyState] = useState(''); const [updating, setUpdating] = useState(false);
  const authedFetch = async (url: string, init?: RequestInit) => { const supabase = createSupabaseBrowserClient(); const { data: { session } } = await supabase.auth.getSession(); return fetch(url, { ...init, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session?.access_token || ''}`, ...(init?.headers || {}) } }); };
  const load = async () => { setError(''); const res = await authedFetch(`/api/project-inquiries/${id}`); const json = await res.json(); if (!res.ok) setError(json.error || 'Gagal memuat detail inquiry.'); else setRow(json.data); };
  useEffect(() => { load(); }, [id]);
  const patch = async (status: ProjectInquiry['status']) => { setUpdating(true); const res = await authedFetch(`/api/project-inquiries/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); if (!res.ok) { const json = await res.json(); setError(json.error || 'Gagal memperbarui status inquiry.'); } await load(); setUpdating(false); };
  const copyMessage = async () => { if (!row) return; await navigator.clipboard.writeText(row.message_preview); setCopyState('Pesan berhasil disalin.'); setTimeout(() => setCopyState(''), 2000); };
  if (!row && !error) return <p className='text-white/60'>Memuat detail...</p>;
  if (error && !row) return <p className='rounded-xl border border-red-400/25 bg-red-500/10 p-3 text-sm text-red-200'>{error}</p>;
  if (!row) return null;
  return <div className='space-y-6'>{error ? <p className='rounded-xl border border-red-400/25 bg-red-500/10 p-3 text-sm text-red-200'>{error}</p> : null}
    <div className='rounded-2xl border border-white/10 bg-white/[0.015] p-5 space-y-3 text-sm'>{[['Nama', row.nama], ['Perusahaan / Brand / Instansi', row.perusahaan || '—'], ['Email', row.email || '—'], ['WhatsApp', row.whatsapp || '—'], ['Jenis kebutuhan', row.jenis_kebutuhan], ['Lokasi project', row.lokasi_project || '—'], ['Estimasi luas', row.estimasi_luas || '—'], ['Tahap project', row.tahap_project || '—'], ['Timeline', row.timeline || '—'], ['Budget range', row.budget_range || '—'], ['Status file', row.status_file || '—'], ['Kebutuhan utama', row.kebutuhan_utama], ['Message preview', row.message_preview], ['Created at', new Date(row.created_at).toLocaleString('id-ID')], ['Current status', row.status]].map(([k, v]) => <p key={String(k)}><span className='text-white/55'>{k}:</span> {String(v)}</p>)}</div>
    <div className='flex flex-wrap gap-3'><button onClick={copyMessage} className='rounded-full border border-white/20 px-4 py-2 text-xs hover:border-[#D4AF37]/45 hover:text-[#D4AF37]'>Salin Pesan WhatsApp</button>{row.whatsapp ? <a className='rounded-full border border-[#D4AF37]/35 px-4 py-2 text-xs text-[#D4AF37]' href={`https://wa.me/${row.whatsapp.replace(/[^\d]/g, '')}?text=${encodeURIComponent(row.message_preview)}`} target='_blank' rel='noreferrer'>Buka WhatsApp</a> : null}<button disabled={updating} onClick={() => patch('ditinjau')} className='rounded-full border border-white/20 px-4 py-2 text-xs disabled:opacity-50'>Tandai Ditinjau</button><button disabled={updating} onClick={() => patch('dihubungi')} className='rounded-full border border-white/20 px-4 py-2 text-xs disabled:opacity-50'>Tandai Dihubungi</button><button disabled={updating} onClick={() => patch('selesai')} className='rounded-full border border-white/20 px-4 py-2 text-xs disabled:opacity-50'>Tandai Selesai</button><button disabled={updating} onClick={() => patch('arsip')} className='rounded-full border border-white/20 px-4 py-2 text-xs disabled:opacity-50'>Arsipkan</button></div>{copyState ? <p className='text-emerald-300 text-xs'>{copyState}</p> : null}</div>;
}
